### ISSUE TITLE
Can just put it in the settings?

### ISSUE THREAD

**Issue by player99963** [hako-mikan/sd-webui-negpip#19]
It's a great extension, I keep it open at all times, so for me it just takes up more space in the t2i and i2i interfaces.
I'd like to get a way to hide it or just move it to settings and just choose to activate it or not from settings.

**Comment by 925-Studio** [comment]
Totally agree!

**Comment by DavideAlidosi** [comment]
Thank's for update, but this broken the extension for me:
`    Traceback (most recent call last):
      File "L:\A1111 Portable\sd.webui\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "L:\A1111 Portable\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "L:\A1111 Portable\sd.webui\webui\extensions\sd-webui-negpip\scripts\negpip.py", line 31, in <module>
        opt_active = getattr(shared.opts,OPT_ACT)
      File "L:\A1111 Portable\sd.webui\webui\modules\options.py", line 117, in __getattr__
        return super(Options, self).__getattribute__(item)
    AttributeError: 'Options' object has no attribute 'negpip_active'`

**Comment by DavideAlidosi** [comment]
Thank's for update, but this broken the extension for me:

```
    Traceback (most recent call last):
      File "L:\A1111 Portable\sd.webui\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "L:\A1111 Portable\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "L:\A1111 Portable\sd.webui\webui\extensions\sd-webui-negpip\scripts\negpip.py", line 31, in <module>
        opt_active = getattr(shared.opts,OPT_ACT)
      File "L:\A1111 Portable\sd.webui\webui\modules\options.py", line 117, in __getattr__
        return super(Options, self).__getattribute__(item)
    AttributeError: 'Options' object has no attribute 'negpip_active'
```

**Comment by hako-mikan** [comment]
Added option to hide in Txt2img/img2img tab.
