### ISSUE TITLE
When I input: (girl:-1.5)

### ISSUE THREAD

**Issue by Tan-TanZi** [hako-mikan/sd-webui-negpip#2]
Error running process_batch: D:\********\********\extensions\sd-webui-negpip\scripts\negpip.py
Traceback (most recent call last):
  File "D:\********\********\modules\scripts.py", line 469, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "D:\********\********\extensions\sd-webui-negpip\scripts\negpip.py", line 98, in process_batch
    self.conds, self.contokens = conddealer(np)
  File "D:\********\********\extensions\sd-webui-negpip\scripts\negpip.py", line 80, in conddealer
    if start is None: start = cond[0][0].cond[0:1,:]
IndexError: list index out of range

**Comment by hako-mikan** [comment]
You are using old version.
Update it and try.
If you get error after update.
Tell me your environment.
