### ISSUE TITLE
Uses wrong path for ui-config.json

### ISSUE THREAD

**Issue by SirVeggie** [hako-mikan/sd-webui-negpip#21]
The script fails to load due to trying to access ui-config.json from the wrong location. This is likely caused by using a launch parameter to set a different path for the file, but the extension doesn't take this into account and tries to use the default path instead.

```
*** Error loading script: negpip.py
Traceback (most recent call last):
File "S:\Library\Files\Tools\sd-webui\modules\scripts.py", line 382, in load_scripts
  script_module = script_loading.load_module(scriptfile.path)
File "S:\Library\Files\Tools\sd-webui\modules\script_loading.py", line 10, in load_module
  module_spec.loader.exec_module(module)
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "S:\Library\Files\Tools\sd-webui\extensions\sd-webui-negpip\scripts\negpip.py", line 23, in <module>
  with open(CONFIG, 'r') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'ui-config.json'
```

**Comment by SirVeggie** [comment]
As a temporary fix I've copied the ui-config.json into the default location to get it to work for now.

**Comment by hako-mikan** [comment]
Fixed.
