### ISSUE TITLE
HiRes Fix時、高解像度step数を0にしているとエラー？

### ISSUE THREAD

**Issue by JujoHotaru** [hako-mikan/sd-webui-negpip#32]
いつもお世話になっております。

WebUI 1.7.0＋NegPiP 本日最新版で、HiRes Fixを有効にし、高解像度でのstep数を0（元出力のサンプリングステップ数指定をそのまま使う）として出力すると、コンソールで以下のエラーが発生していました。

この場合、出力自体は行われるのですが、マイナス指定プロンプトが入っていてもNegPiPが効かなくなっているようです。

```
** Error running process_batch: C:\stable-diffusion-webui\extensions\sd-webui-negpip\scripts\negpip.py [00:00<?, ?it/s]
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\modules\scripts.py", line 742, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "C:\stable-diffusion-webui\extensions\sd-webui-negpip\scripts\negpip.py", line 160, in process_batch
        if self.hrp: scheduled_hr_p = prompt_parser.get_learned_conditioning_prompt_schedules(p.hr_prompts,p.hr_second_pass_steps if p.hr_second_pass_steps > 0 else p.step)
    AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'step'
```

WebUI 1.6.0を使っていたときは発生していなかった症状と思われます。

**Comment by aolko** [comment]
Same here, any fix?

**Comment by hako-mikan** [comment]
修正しました。
