### ISSUE TITLE
使用 Commit 773eb87 版本时运行错误

### ISSUE THREAD

**Issue by trojan-uma** [hako-mikan/sd-webui-negpip#41]
在使用 Commit 773eb87 版本时控制台会输出以下错误信息并无法正常使用（仅在t2i测试）。

```
……
postprocess_batch
LoRA Block weight (lora): loraname: (Te:0.8,Unet:0.8) x [1.0, 0, 1.0, 1.0, 0, 1.0, 1.0, 0, 1.0, 1.0, 0, 0, 0, 1.0, 0, 0, 0, 1.0, 1.0, 1.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0]
LoRA Block weight (lora): loraname: (Te:0.8,Unet:0.8) x [1.0, 0, 1.0, 1.0, 0, 1.0, 1.0, 0, 1.0, 1.0, 0, 0, 0, 1.0, 0, 0, 0, 1.0, 1.0, 1.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0]
LoRA Block weight (lora): loraname: (Te:0.4,Unet:0.4) x [1.0, 0, 1.0, 1.0, 0, 1.0, 1.0, 0, 1.0, 1.0, 0, 0, 0, 1.0, 0, 0, 0, 1.0, 1.0, 1.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0]
LoRA Block weight (lora): loraname: (Te:0.8,Unet:0.8) x [1.0, 0, 1.0, 1.0, 0, 1.0, 1.0, 0, 0.0, 0.0, 0, 0, 0, 0.0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0]
*** Error running process_batch: X:\root\extensions\sd-webui-negpip\scripts\negpip.py
    Traceback (most recent call last):
      File "X:\root\modules\scripts.py", line 864, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "X:\root\extensions\sd-webui-negpip\scripts\negpip.py", line 214, in process_batch
        self.conds_all = calcconds(nip)
      File "X:\root\extensions\sd-webui-negpip\scripts\negpip.py", line 206, in calcconds
        conds, contokens = conddealer(targets)
      File "X:\root\extensions\sd-webui-negpip\scripts\negpip.py", line 179, in conddealer
        with devices.autocast():
    NameError: name 'devices' is not defined
……
```

**Comment by hako-mikan** [comment]
Thanks! Fixed.
