### ISSUE TITLE
AttributeError: 'StableDiffusionXL' object has no attribute 'text_processing_engine' (Forge)

### ISSUE THREAD

**Issue by zzz7xz** [hako-mikan/sd-webui-negpip#43]
Always thankful for your wonderful extensions!
When I activate this extension in the Forge, the following message appears, 

```
*** Error running process_batch: H:\webui_forge_cu121_torch231\webui\extensions\sd-webui-negpip\scripts\negpip.py
    Traceback (most recent call last):
      File "H:\webui_forge_cu121_torch231\webui\modules\scripts.py", line 884, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "H:\webui_forge_cu121_torch231\webui\extensions\sd-webui-negpip\scripts\negpip.py", line 124, in process_batch
        tokenizer = p.sd_model.text_processing_engine.tokenize_line
    AttributeError: 'StableDiffusionXL' object has no attribute 'text_processing_engine'
```

When a prompt with a weight below 0 is set, the image glitches.

WebUI Forge: f2.0.1v1.10.1-previous-552-g953e3f39

**Comment by zzz7xz** [comment]
Just tweaked a few lines, and it seems to work!

line:124
```
tokenizer = p.sd_model.text_processing_engine_l.tokenize_line
```
line:186-189
```
cond_data = cond[0][0].cond
start = cond_data['crossattn'][0:1, :] if self.isxl else cond_data['crossattn'][0:1, :]
end = cond_data['crossattn'][-1:, :] if self.isxl else cond_data['crossattn'][-1:, :]
token, tokenlen = tokenizer(target[0])
conds.append(cond_data['crossattn'][1:tokenlen + 2, :] if self.isxl else cond_data['crossattn'][1:tokenlen + 2, :])
```

**Comment by EveKaczmarek** [comment]
Hey @zzz7xz 

I took your fix and turned it into a pull request. Hope you don't mind!

**Comment by zzz7xz** [comment]
Thanks! I haven’t tested it much, so there could possibly be some issues.
