### ISSUE TITLE
IndexError: too many indices for tensor of dimension 2

### ISSUE THREAD

**Issue by trojan-uma** [hako-mikan/sd-webui-negpip#49]
Error Version: Commit 44ccc26 and after.

```
Error info:
LoRA Block weight (lora): loraname: (Te:0.4,Unet:0.4) x [1.0, 0, 1.0, 1.0, 0, 1.0, 1.0, 0, 1.0, 1.0, 0, 0, 0, 1.0, 0, 0, 0, 1.0, 1.0, 1.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0]
LoRA Block weight (lora): loraname: (Te:0.6,Unet:0.6) x [1.0, 0, 1.0, 1.0, 0, 1.0, 1.0, 0, 1.0, 1.0, 0, 0, 0, 1.0, 0, 0, 0, 1.0, 1.0, 1.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0]
LoRA Block weight (lora): loraname: (Te:0.6,Unet:0.6) x [1.0, 0, 0.0, 0.0, 0, 0.0, 0.0, 0, 0.0, 0.2, 0, 0, 0, 1.0, 0, 0, 0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
LoRA Block weight (lora): loraname: (Te:0.8,Unet:0.8) x [1.0, 0, 1.0, 1.0, 0, 1.0, 1.0, 0, 0.0, 0.0, 0, 0, 0, 0.0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0]
*** Error running process_batch: X:\...\extensions\sd-webui-negpip\scripts\negpip.py
    Traceback (most recent call last):
      File "X:\...\modules\scripts.py", line 864, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "X:\...\extensions\sd-webui-negpip\scripts\negpip.py", line 240, in process_batch
        self.conds_all = calcconds(nip)
      File "X:\...\extensions\sd-webui-negpip\scripts\negpip.py", line 232, in calcconds
        conds, contokens = conddealer(targets)
      File "X:\...\extensions\sd-webui-negpip\scripts\negpip.py", line 207, in conddealer
        if start is None: start = cond_data[cond_key][0:1, :] if not self.isxl else cond_data[cond_key][0:1, :]
    IndexError: too many indices for tensor of dimension 2

---
```

**Comment by hako-mikan** [comment]
Thanks. Fixed.
