### ISSUE TITLE
`TypeError: 'NoneType' object is not subscriptable` raised in denoiser_callback

### ISSUE THREAD

**Issue by touensen** [hako-mikan/sd-webui-negpip#9]
SD v1.5.2 c9c8485bc1e8720aba70f029d25cba1c4abf2b5c, ADetailer v23.9.3, Python v3.10.6

i2tで ADetailer を有効にしていたところ ADetailer の実行中に下記が連続して発生しました。
```
*** Error executing callback cfg_denoiser_callback for C:\sd.webui\webui\extensions\sd-webui-negpip\scripts\negpip.py
    Traceback (most recent call last):
      File "C:\sd.webui\webui\modules\script_callbacks.py", line 195, in cfg_denoiser_callback
        c.callback(params)
      File "C:\sd.webui\webui\extensions\sd-webui-negpip\scripts\negpip.py", line 191, in denoiser_callback
        for step, regions in self.conds_all[0]:
    TypeError: 'NoneType' object is not subscriptable
```

`postprocess` の下記をコメントアウトしたら発生しなくなりましたが対応として正しいかは分かりません。ご報告まで。
```
    def postprocess(self, p, processed, *args):
        if hasattr(self,"handle"):
            hook_forwards(self, p.sd_model.model.diffusion_model, remove=True)
            del self.handle
        # self.conds_all = None
        # self.unconds_all = None
```

**Comment by hako-mikan** [comment]
併用は可能です。
Web-uiのSetting - ADetailerにある
Script names to apply to ADetailer (separated by comma)
にnegpipを加えることで有効になります。

**Comment by zzz7xz** [comment]
ありがとうございます！併用できました！
ADetailer側から設定できたんですね。
失礼いたしました。
